clubs_list = ["Paris-Saint-Germain", "Lens", "Brest", "Nice", "Toulouse", "Le-Havre", "Lorient", "Monaco", "Strasbourg", "Marseille", "Lille", "Reims", "Lyon", "Montpellier", "Metz", "Rennes", 
              "Nantes", "Clermont-Foot", "Bochum", "Mainz-05", "FC-Heidenheim", "Darmstadt", "FC-Koln", "Borussia-Dortmund", "Vfb-Stuttgart", "Bayer-Leverkusen", "Bayern-Munich", "Augsburg", 
              "Freiburg", "Werder-Bremen", "Union-Berlin", "Eintracht-Frankfurt", "Wolfsburg", "Borussia-M-Gladbach", "Hoffenheim", "RB-Leipzig", "Manchester-City", "Manchester-United", 
              "Sheffield-United", "Arsenal", "Liverpool", "West-Ham", "Aston-Villa", "Newcastle", "Brentford", "Brighton", "Crystal-Palace", "Bournemouth", "Nottingham-Forest", "Fulham", "Burnley",
              "Tottenham", "Wolves", "Everton", "Luton", "Chelsea", "Villarreal", "Mallorca", "Real-Madrid", "Sevilla", "Athletic-Club", "Celta-Vigo", "Real-Betis", "Deportivo-Alaves", 
              "Barcelona", "Girona", "Osasuna", "Atletico-Madrid", "Getafe", "Cadiz", "Almeria", "Granada", "Rayo-Vallecano", "Valencia", "Real-Sociedad", "Las-Palmas", "Udinese", "Cagliari", 
              "Juventus", "Sassuolo", "Empoli", "Lecce", "Roma", "Verona", "Salernitana", "Genoa", "Fiorentina", "Napoli", "Bologna", "Atalanta", "Monza", "Lazio", "Torino", 
              "Frosinone", "Inter", "AC-Milan"]


clubs_ids = {"Paris-Saint-Germain": 304,
             "Strasbourg": 148,
             "Lille": 607,
             "Nantes": 302,
             "Rennes": 313,
             "Monaco": 248,
             "Reims": 950,
             "Metz": 314,
             "Brest": 2332,
             "Le-Havre": 217,
             "Lens": 309,
             "Nice": 613,
             "Clermont-Foot":941,
             "Lorient": 146,
             "Montpellier": 311,
             "Marseille": 249,
             "Toulouse": 246,
             "Lyon": 228,
             "Bayer-Leverkusen": 36,
             "Darmstadt": 1147,
             "Bayern-Munich": 37,
             "FC-Heidenheim": 4852,
             "Mainz-05": 219,
             "FC-Koln": 282,
             "Wolfsburg": 33,
             "Eintracht-Frankfurt": 45,
             "Bochum": 109,
             "Borussia-M-Gladbach": 134,
             "VfB Stuttgart": 41,
             "Augsburg": 1730,
             "RB-Leipzig": 7614,
             "Freiburg": 50,
             "Werder-Bremen": 42,
             "Union-Berlin": 796,
             "Borussia-Dortmund": 44,
             "Hoffenheim": 1211,
             "Manchester-City": 167, 
             "Manchester-United": 32, 
              "Sheffield-United": 163, 
              "Arsenal": 13, 
              "Liverpool": 26, 
              "West-Ham": 29, 
              "Aston-Villa": 24, 
              "Newcastle": 23, 
              "Brentford": 189, 
              "Brighton": 211, 
              "Crystal-Palace": 162, 
              "Bournemouth": 183, 
              "Nottingham-Forest": 174, 
              "Fulham": 170, 
              "Burnley": 184,
              "Tottenham": 30, 
              "Wolves": 161, 
              "Everton": 31, 
              "Luton": 95, 
              "Chelsea": 15, 
              "Villarreal": 839, 
              "Mallorca": 51, 
              "Real-Madrid": 52, 
              "Sevilla": 67, 
              "Athletic-Club": 53, 
              "Celta-Vigo": 62, 
              "Real-Betis": 54, 
              "Deportivo-Alaves": 60, 
              "Barcelona": 65, 
              "Girona": 2783, 
              "Osasuna": 131, 
              "Atletico-Madrid": 63, 
              "Getafe": 819, 
              "Cadiz": 1354, 
              "Almeria": 1799, 
              "Granada": 925, 
              "Rayo-Vallecano": 64, 
              "Valencia": 55, 
              "Real-Sociedad": 68, 
              "Las-Palmas": 838, 
              "Udinese": 86, 
              "Cagliari": 78, 
              "Juventus": 87, 
              "Sassuolo": 2889, 
              "Empoli": 272, 
              "Lecce": 79, 
              "Roma": 84, 
              "Verona": 76, 
              "Salernitana": 143, 
              "Genoa": 278, 
              "Fiorentina": 73, 
              "Napoli": 276, 
              "Bologna": 71, 
              "Atalanta": 300, 
              "Monza": 269, 
              "Lazio": 77, 
              "Torino": 72, 
              "Frosinone": 2732, 
              "Inter": 75, 
              "AC-Milan": 80}

